package com.example.rcp.domain;

import java.util.Date;

public class VisitorCompanys {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_company_id
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private Integer visitor_company_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_company_name
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private String visitor_company_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_cpmpany_hiragana
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private String visitor_cpmpany_hiragana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_company_oldname
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private String visitor_company_oldname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_company_oldname_hiragana
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private String visitor_company_oldname_hiragana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_company_reg_date
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private Date visitor_company_reg_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitor_companys.visitor_company_mod_date
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	private Date visitor_company_mod_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_company_id
	 * @return  the value of visitor_companys.visitor_company_id
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public Integer getVisitor_company_id() {
		return visitor_company_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_company_id
	 * @param visitor_company_id  the value for visitor_companys.visitor_company_id
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_company_id(Integer visitor_company_id) {
		this.visitor_company_id = visitor_company_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_company_name
	 * @return  the value of visitor_companys.visitor_company_name
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public String getVisitor_company_name() {
		return visitor_company_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_company_name
	 * @param visitor_company_name  the value for visitor_companys.visitor_company_name
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_company_name(String visitor_company_name) {
		this.visitor_company_name = visitor_company_name == null ? null : visitor_company_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_cpmpany_hiragana
	 * @return  the value of visitor_companys.visitor_cpmpany_hiragana
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public String getVisitor_cpmpany_hiragana() {
		return visitor_cpmpany_hiragana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_cpmpany_hiragana
	 * @param visitor_cpmpany_hiragana  the value for visitor_companys.visitor_cpmpany_hiragana
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_cpmpany_hiragana(String visitor_cpmpany_hiragana) {
		this.visitor_cpmpany_hiragana = visitor_cpmpany_hiragana == null ? null : visitor_cpmpany_hiragana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_company_oldname
	 * @return  the value of visitor_companys.visitor_company_oldname
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public String getVisitor_company_oldname() {
		return visitor_company_oldname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_company_oldname
	 * @param visitor_company_oldname  the value for visitor_companys.visitor_company_oldname
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_company_oldname(String visitor_company_oldname) {
		this.visitor_company_oldname = visitor_company_oldname == null ? null : visitor_company_oldname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_company_oldname_hiragana
	 * @return  the value of visitor_companys.visitor_company_oldname_hiragana
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public String getVisitor_company_oldname_hiragana() {
		return visitor_company_oldname_hiragana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_company_oldname_hiragana
	 * @param visitor_company_oldname_hiragana  the value for visitor_companys.visitor_company_oldname_hiragana
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_company_oldname_hiragana(String visitor_company_oldname_hiragana) {
		this.visitor_company_oldname_hiragana = visitor_company_oldname_hiragana == null ? null
				: visitor_company_oldname_hiragana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_company_reg_date
	 * @return  the value of visitor_companys.visitor_company_reg_date
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public Date getVisitor_company_reg_date() {
		return visitor_company_reg_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_company_reg_date
	 * @param visitor_company_reg_date  the value for visitor_companys.visitor_company_reg_date
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_company_reg_date(Date visitor_company_reg_date) {
		this.visitor_company_reg_date = visitor_company_reg_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitor_companys.visitor_company_mod_date
	 * @return  the value of visitor_companys.visitor_company_mod_date
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public Date getVisitor_company_mod_date() {
		return visitor_company_mod_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitor_companys.visitor_company_mod_date
	 * @param visitor_company_mod_date  the value for visitor_companys.visitor_company_mod_date
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setVisitor_company_mod_date(Date visitor_company_mod_date) {
		this.visitor_company_mod_date = visitor_company_mod_date;
	}
}