package com.example.rcp.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VisitorCompanysExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public VisitorCompanysExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andVisitor_company_idIsNull() {
			addCriterion("visitor_company_id is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idIsNotNull() {
			addCriterion("visitor_company_id is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idEqualTo(Integer value) {
			addCriterion("visitor_company_id =", value, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idNotEqualTo(Integer value) {
			addCriterion("visitor_company_id <>", value, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idGreaterThan(Integer value) {
			addCriterion("visitor_company_id >", value, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("visitor_company_id >=", value, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idLessThan(Integer value) {
			addCriterion("visitor_company_id <", value, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idLessThanOrEqualTo(Integer value) {
			addCriterion("visitor_company_id <=", value, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idIn(List<Integer> values) {
			addCriterion("visitor_company_id in", values, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idNotIn(List<Integer> values) {
			addCriterion("visitor_company_id not in", values, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idBetween(Integer value1, Integer value2) {
			addCriterion("visitor_company_id between", value1, value2, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_idNotBetween(Integer value1, Integer value2) {
			addCriterion("visitor_company_id not between", value1, value2, "visitor_company_id");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameIsNull() {
			addCriterion("visitor_company_name is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameIsNotNull() {
			addCriterion("visitor_company_name is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameEqualTo(String value) {
			addCriterion("visitor_company_name =", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameNotEqualTo(String value) {
			addCriterion("visitor_company_name <>", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameGreaterThan(String value) {
			addCriterion("visitor_company_name >", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameGreaterThanOrEqualTo(String value) {
			addCriterion("visitor_company_name >=", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameLessThan(String value) {
			addCriterion("visitor_company_name <", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameLessThanOrEqualTo(String value) {
			addCriterion("visitor_company_name <=", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameLike(String value) {
			addCriterion("visitor_company_name like", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameNotLike(String value) {
			addCriterion("visitor_company_name not like", value, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameIn(List<String> values) {
			addCriterion("visitor_company_name in", values, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameNotIn(List<String> values) {
			addCriterion("visitor_company_name not in", values, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameBetween(String value1, String value2) {
			addCriterion("visitor_company_name between", value1, value2, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_nameNotBetween(String value1, String value2) {
			addCriterion("visitor_company_name not between", value1, value2, "visitor_company_name");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaIsNull() {
			addCriterion("visitor_cpmpany_hiragana is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaIsNotNull() {
			addCriterion("visitor_cpmpany_hiragana is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaEqualTo(String value) {
			addCriterion("visitor_cpmpany_hiragana =", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaNotEqualTo(String value) {
			addCriterion("visitor_cpmpany_hiragana <>", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaGreaterThan(String value) {
			addCriterion("visitor_cpmpany_hiragana >", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaGreaterThanOrEqualTo(String value) {
			addCriterion("visitor_cpmpany_hiragana >=", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaLessThan(String value) {
			addCriterion("visitor_cpmpany_hiragana <", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaLessThanOrEqualTo(String value) {
			addCriterion("visitor_cpmpany_hiragana <=", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaLike(String value) {
			addCriterion("visitor_cpmpany_hiragana like", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaNotLike(String value) {
			addCriterion("visitor_cpmpany_hiragana not like", value, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaIn(List<String> values) {
			addCriterion("visitor_cpmpany_hiragana in", values, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaNotIn(List<String> values) {
			addCriterion("visitor_cpmpany_hiragana not in", values, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaBetween(String value1, String value2) {
			addCriterion("visitor_cpmpany_hiragana between", value1, value2, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_cpmpany_hiraganaNotBetween(String value1, String value2) {
			addCriterion("visitor_cpmpany_hiragana not between", value1, value2, "visitor_cpmpany_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameIsNull() {
			addCriterion("visitor_company_oldname is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameIsNotNull() {
			addCriterion("visitor_company_oldname is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameEqualTo(String value) {
			addCriterion("visitor_company_oldname =", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameNotEqualTo(String value) {
			addCriterion("visitor_company_oldname <>", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameGreaterThan(String value) {
			addCriterion("visitor_company_oldname >", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameGreaterThanOrEqualTo(String value) {
			addCriterion("visitor_company_oldname >=", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameLessThan(String value) {
			addCriterion("visitor_company_oldname <", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameLessThanOrEqualTo(String value) {
			addCriterion("visitor_company_oldname <=", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameLike(String value) {
			addCriterion("visitor_company_oldname like", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameNotLike(String value) {
			addCriterion("visitor_company_oldname not like", value, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameIn(List<String> values) {
			addCriterion("visitor_company_oldname in", values, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameNotIn(List<String> values) {
			addCriterion("visitor_company_oldname not in", values, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameBetween(String value1, String value2) {
			addCriterion("visitor_company_oldname between", value1, value2, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldnameNotBetween(String value1, String value2) {
			addCriterion("visitor_company_oldname not between", value1, value2, "visitor_company_oldname");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaIsNull() {
			addCriterion("visitor_company_oldname_hiragana is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaIsNotNull() {
			addCriterion("visitor_company_oldname_hiragana is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaEqualTo(String value) {
			addCriterion("visitor_company_oldname_hiragana =", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaNotEqualTo(String value) {
			addCriterion("visitor_company_oldname_hiragana <>", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaGreaterThan(String value) {
			addCriterion("visitor_company_oldname_hiragana >", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaGreaterThanOrEqualTo(String value) {
			addCriterion("visitor_company_oldname_hiragana >=", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaLessThan(String value) {
			addCriterion("visitor_company_oldname_hiragana <", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaLessThanOrEqualTo(String value) {
			addCriterion("visitor_company_oldname_hiragana <=", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaLike(String value) {
			addCriterion("visitor_company_oldname_hiragana like", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaNotLike(String value) {
			addCriterion("visitor_company_oldname_hiragana not like", value, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaIn(List<String> values) {
			addCriterion("visitor_company_oldname_hiragana in", values, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaNotIn(List<String> values) {
			addCriterion("visitor_company_oldname_hiragana not in", values, "visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaBetween(String value1, String value2) {
			addCriterion("visitor_company_oldname_hiragana between", value1, value2,
					"visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_oldname_hiraganaNotBetween(String value1, String value2) {
			addCriterion("visitor_company_oldname_hiragana not between", value1, value2,
					"visitor_company_oldname_hiragana");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateIsNull() {
			addCriterion("visitor_company_reg_date is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateIsNotNull() {
			addCriterion("visitor_company_reg_date is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateEqualTo(Date value) {
			addCriterion("visitor_company_reg_date =", value, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateNotEqualTo(Date value) {
			addCriterion("visitor_company_reg_date <>", value, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateGreaterThan(Date value) {
			addCriterion("visitor_company_reg_date >", value, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("visitor_company_reg_date >=", value, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateLessThan(Date value) {
			addCriterion("visitor_company_reg_date <", value, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateLessThanOrEqualTo(Date value) {
			addCriterion("visitor_company_reg_date <=", value, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateIn(List<Date> values) {
			addCriterion("visitor_company_reg_date in", values, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateNotIn(List<Date> values) {
			addCriterion("visitor_company_reg_date not in", values, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateBetween(Date value1, Date value2) {
			addCriterion("visitor_company_reg_date between", value1, value2, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_reg_dateNotBetween(Date value1, Date value2) {
			addCriterion("visitor_company_reg_date not between", value1, value2, "visitor_company_reg_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateIsNull() {
			addCriterion("visitor_company_mod_date is null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateIsNotNull() {
			addCriterion("visitor_company_mod_date is not null");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateEqualTo(Date value) {
			addCriterion("visitor_company_mod_date =", value, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateNotEqualTo(Date value) {
			addCriterion("visitor_company_mod_date <>", value, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateGreaterThan(Date value) {
			addCriterion("visitor_company_mod_date >", value, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("visitor_company_mod_date >=", value, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateLessThan(Date value) {
			addCriterion("visitor_company_mod_date <", value, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateLessThanOrEqualTo(Date value) {
			addCriterion("visitor_company_mod_date <=", value, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateIn(List<Date> values) {
			addCriterion("visitor_company_mod_date in", values, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateNotIn(List<Date> values) {
			addCriterion("visitor_company_mod_date not in", values, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateBetween(Date value1, Date value2) {
			addCriterion("visitor_company_mod_date between", value1, value2, "visitor_company_mod_date");
			return (Criteria) this;
		}

		public Criteria andVisitor_company_mod_dateNotBetween(Date value1, Date value2) {
			addCriterion("visitor_company_mod_date not between", value1, value2, "visitor_company_mod_date");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table visitor_companys
	 * @mbg.generated  Sat Aug 28 02:17:07 JST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visitor_companys
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 28 00:17:01 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}